Repository Noostak/Noostak-Server, pull requests merged in 2025-02, with the labels that each got.

#12 [chore] 패키지 구조 설계
  src/main/java/org/noostak/appointment/api/temp
  src/main/java/org/noostak/appointment/application/temp
  src/main/java/org/noostak/appointment/common/exception/temp
  src/main/java/org/noostak/appointment/common/success/temp
  src/main/java/org/noostak/appointment/domain/temp
  src/main/java/org/noostak/appointment/dto/temp
  src/main/java/org/noostak/appointmentMember/api/temp
  src/main/java/org/noostak/appointmentMember/application/temp
  src/main/java/org/noostak/appointmentMember/common/exception/temp
  src/main/java/org/noostak/appointmentMember/common/success/temp
  src/main/java/org/noostak/appointmentMember/domain/temp
  src/main/java/org/noostak/appointmentMember/dto/temp
  src/main/java/org/noostak/appointmentOption/api/temp
  src/main/java/org/noostak/appointmentOption/application/temp
  src/main/java/org/noostak/appointmentOption/common/exception/temp
  src/main/java/org/noostak/appointmentOption/common/success/temp
  src/main/java/org/noostak/appointmentOption/domain/temp
  src/main/java/org/noostak/appointmentOption/dto/temp
  src/main/java/org/noostak/global/entity/temp
  src/main/java/org/noostak/global/error/temp
  src/main/java/org/noostak/global/request/temp
  src/main/java/org/noostak/global/response/temp
  src/main/java/org/noostak/global/success/temp
  src/main/java/org/noostak/group/api/temp
  src/main/java/org/noostak/group/application/temp
  src/main/java/org/noostak/group/common/exception/temp
  src/main/java/org/noostak/group/common/success/temp
  src/main/java/org/noostak/group/domain/temp
  src/main/java/org/noostak/group/dto/temp
  src/main/java/org/noostak/likes/api/temp
  src/main/java/org/noostak/likes/application/temp
  src/main/java/org/noostak/likes/common/exception/temp
  src/main/java/org/noostak/likes/common/success/temp
  src/main/java/org/noostak/likes/domain/temp
  src/main/java/org/noostak/likes/dto/temp
  src/main/java/org/noostak/member-group/api/temp
  src/main/java/org/noostak/member-group/application/temp
  src/main/java/org/noostak/member-group/common/exception/temp
  src/main/java/org/noostak/member-group/common/success/temp
  src/main/java/org/noostak/member-group/domain/temp
  src/main/java/org/noostak/member-group/dto/temp
  src/main/java/org/noostak/member/api/temp
  src/main/java/org/noostak/member/application/temp
  src/main/java/org/noostak/member/common/exception/temp
  src/main/java/org/noostak/member/common/success/temp
  src/main/java/org/noostak/member/domain/temp
  src/main/java/org/noostak/member/dto/temp
Labels: 🐋 장순 🐋, 🗂 chore, 🦖 용태 🦖

#20 [feat] AWS S3 Service 연동
  .github/workflows/DOCKER-CD-PROD.yml
  .github/workflows/DOCKER-CD-STAGING.yml
  build.gradle
  src/main/java/org/noostak/global/config/AwsConfig.java
  src/main/java/org/noostak/infra/FakeS3StorageImpl.java
  src/main/java/org/noostak/infra/S3Service.java
  src/main/java/org/noostak/infra/S3Storage.java
  src/main/java/org/noostak/infra/S3StorageImpl.java
  src/main/java/org/noostak/infra/error/S3UploadErrorCode.java
  src/main/java/org/noostak/infra/error/S3UploadException.java
  src/test/java/org/noostak/infra/S3ServiceTest.java
Labels: ✨ feat, 🦖 용태 🦖

#30 [refactor] 멤버 이름 검증 방식 변경 (블랙 리스트 -> 화이트 리스트)
  src/main/java/org/noostak/member/common/MemberErrorCode.java
  src/main/java/org/noostak/member/domain/vo/MemberName.java
  src/test/java/org/noostak/NoostakApplicationTests.java
  src/test/java/org/noostak/member/domain/vo/AuthIdTest.java
  src/test/java/org/noostak/member/domain/vo/MemberNameTest.java
  src/test/java/org/noostak/member/domain/vo/MemberProfileImageKeyTest.java
Labels: ♻️ refactor, 🐋 장순 🐋

#32 [feat] 약속 멤버 엔티티 구현
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMember.java
  src/main/java/org/noostak/appointmentmember/domain/vo/AppointmentAvailability.java
  src/main/java/org/noostak/appointmentoption/domain/temp
Labels: ✨ feat, 🦖 용태 🦖

#31 [feat] 좋아요 엔티티 구현
  src/main/java/org/noostak/global/error/core/ErrorCode.java
  src/main/java/org/noostak/likes/common/LikesErrorCode.java
  src/main/java/org/noostak/likes/common/LikesException.java
  src/main/java/org/noostak/likes/common/exception/temp
  src/main/java/org/noostak/likes/common/success/temp
  src/main/java/org/noostak/likes/domain/Likes.java
  src/main/java/org/noostak/likes/domain/temp
  src/main/java/org/noostak/likes/domain/vo/LikesCount.java
  src/test/java/org/noostak/likes/domain/vo/LikesCountTest.java
Labels: ✨ feat, 🦖 용태 🦖

#33 [feat] 그룹 도메인 구현
  src/main/java/org/noostak/group/application/InviteCodeGenerator.java
  src/main/java/org/noostak/group/application/temp
  src/main/java/org/noostak/group/common/exception/GroupErrorCode.java
  src/main/java/org/noostak/group/common/exception/GroupException.java
  src/main/java/org/noostak/group/common/exception/temp
  src/main/java/org/noostak/group/config/InviteCodeGeneratorConfig.java
  src/main/java/org/noostak/group/domain/DefaultInviteCodePolicy.java
  src/main/java/org/noostak/group/domain/Group.java
  src/main/java/org/noostak/group/domain/InviteCodePolicy.java
  src/main/java/org/noostak/group/domain/temp
  src/main/java/org/noostak/group/domain/vo/GroupInvitationCode.java
  src/main/java/org/noostak/group/domain/vo/GroupMemberCount.java
  src/main/java/org/noostak/group/domain/vo/GroupName.java
  src/main/java/org/noostak/group/domain/vo/GroupProfileImageKey.java
  src/test/java/org/noostak/group/domain/vo/GroupInvitationCodeTest.java
  src/test/java/org/noostak/group/domain/vo/GroupMemberCountTest.java
  src/test/java/org/noostak/group/domain/vo/GroupNameTest.java
Labels: ✨ feat, 🐋 장순 🐋

#37 [feat] 약속 엔티티 구현
  src/main/java/org/noostak/appointment/common/exception/AppointmentErrorCode.java
  src/main/java/org/noostak/appointment/common/exception/AppointmentException.java
  src/main/java/org/noostak/appointment/domain/Appointment.java
  src/main/java/org/noostak/appointment/domain/temp
  src/main/java/org/noostak/appointment/domain/vo/AppointmentCategory.java
  src/main/java/org/noostak/appointment/domain/vo/AppointmentDuration.java
  src/main/java/org/noostak/appointment/domain/vo/AppointmentMemberCount.java
  src/main/java/org/noostak/appointment/domain/vo/AppointmentStatus.java
  src/test/java/org/noostak/appointment/domain/vo/AppointmentCategoryTest.java
  src/test/java/org/noostak/appointment/domain/vo/AppointmentDurationTest.java
  src/test/java/org/noostak/appointment/domain/vo/AppointmentMemberCountTest.java
  src/test/java/org/noostak/member/domain/vo/MemberNameTest.java
Labels: ✨ feat, 🐋 장순 🐋

#35 [feat] 약속 호스트 선택 시간 엔티티 구현
  src/main/java/org/noostak/appointment/domain/AppointmentHostSelectionTimes.java
Labels: ✨ feat, 🦖 용태 🦖

#45 [feat] 멤버 그룹 엔티티 구현
  src/main/java/org/noostak/membergroup/domain/MemberGroups.java
Labels: ✨ feat, 🐋 장순 🐋, 🦖 용태 🦖

#46 [🧬 merge] 엔티티 구현
  src/main/java/org/noostak/appointment/common/exception/AppointmentErrorCode.java
  src/main/java/org/noostak/appointment/common/exception/AppointmentException.java
  src/main/java/org/noostak/appointment/domain/Appointment.java
  src/main/java/org/noostak/appointment/domain/AppointmentHostSelectionTimes.java
  src/main/java/org/noostak/appointment/domain/temp
  src/main/java/org/noostak/appointment/domain/vo/AppointmentCategory.java
  src/main/java/org/noostak/appointment/domain/vo/AppointmentDuration.java
  src/main/java/org/noostak/appointment/domain/vo/AppointmentMemberCount.java
  src/main/java/org/noostak/appointment/domain/vo/AppointmentStatus.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMember.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberAvailableTimes.java
  src/main/java/org/noostak/appointmentmember/domain/temp
  src/main/java/org/noostak/appointmentmember/domain/vo/AppointmentAvailability.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOption.java
  src/main/java/org/noostak/appointmentoption/domain/temp
  src/main/java/org/noostak/appointmentoption/domain/vo/AppointmentOptionStatus.java
  src/main/java/org/noostak/global/error/core/ErrorCode.java
  src/main/java/org/noostak/group/application/InviteCodeGenerator.java
  src/main/java/org/noostak/group/application/temp
  src/main/java/org/noostak/group/common/exception/GroupErrorCode.java
  src/main/java/org/noostak/group/common/exception/GroupException.java
  src/main/java/org/noostak/group/common/exception/temp
  src/main/java/org/noostak/group/config/InviteCodeGeneratorConfig.java
  src/main/java/org/noostak/group/domain/DefaultInviteCodePolicy.java
  src/main/java/org/noostak/group/domain/Groups.java
  src/main/java/org/noostak/group/domain/InviteCodePolicy.java
  src/main/java/org/noostak/group/domain/temp
  src/main/java/org/noostak/group/domain/vo/GroupInvitationCode.java
  src/main/java/org/noostak/group/domain/vo/GroupMemberCount.java
  src/main/java/org/noostak/group/domain/vo/GroupName.java
  src/main/java/org/noostak/group/domain/vo/GroupProfileImageKey.java
  src/main/java/org/noostak/likes/common/LikesErrorCode.java
  src/main/java/org/noostak/likes/common/LikesException.java
  src/main/java/org/noostak/likes/common/exception/temp
  src/main/java/org/noostak/likes/common/success/temp
  src/main/java/org/noostak/likes/domain/Likes.java
  src/main/java/org/noostak/likes/domain/temp
  src/main/java/org/noostak/likes/domain/vo/LikesCount.java
  src/main/java/org/noostak/member/common/MemberErrorCode.java
  src/main/java/org/noostak/member/domain/Member.java
  src/main/java/org/noostak/member/domain/vo/MemberName.java
  src/main/java/org/noostak/membergroup/domain/MemberGroups.java
  src/test/java/org/noostak/NoostakApplicationTests.java
  src/test/java/org/noostak/appointment/domain/vo/AppointmentCategoryTest.java
  src/test/java/org/noostak/appointment/domain/vo/AppointmentDurationTest.java
  src/test/java/org/noostak/appointment/domain/vo/AppointmentMemberCountTest.java
  src/test/java/org/noostak/group/domain/vo/GroupsInvitationCodeTest.java
  src/test/java/org/noostak/group/domain/vo/GroupsMemberCountTest.java
  src/test/java/org/noostak/group/domain/vo/GroupsNameTest.java
  src/test/java/org/noostak/likes/domain/vo/LikesCountTest.java
  src/test/java/org/noostak/member/domain/vo/AuthIdTest.java
  src/test/java/org/noostak/member/domain/vo/MemberNameTest.java
  src/test/java/org/noostak/member/domain/vo/MemberProfileImageKeyTest.java
Labels: 🐋 장순 🐋, 🧬 merge, 🦖 용태 🦖

#51 [feat] S3Service 기능 추가 및 upload 반환 데이터 수정
  src/main/java/org/noostak/infra/KeyAndUrl.java
  src/main/java/org/noostak/infra/S3DirectoryPath.java
  src/main/java/org/noostak/infra/S3Service.java
  src/main/java/org/noostak/infra/S3ServiceImpl.java
  src/main/java/org/noostak/infra/S3Storage.java
  src/main/java/org/noostak/infra/S3StorageImpl.java
  src/test/java/org/noostak/infra/FakeS3StorageImpl.java
  src/test/java/org/noostak/infra/S3ServiceTest.java
Labels: ♻️ refactor, 🦖 용태 🦖

#52 [✨ feat] 그룹 생성 API 구현
  src/main/java/org/noostak/NoostakApplication.java
  src/main/java/org/noostak/appointment/domain/Appointment.java
  src/main/java/org/noostak/group/api/GroupController.java
  src/main/java/org/noostak/group/api/temp
  src/main/java/org/noostak/group/application/GroupCreateService.java
  src/main/java/org/noostak/group/application/GroupCreateServiceImpl.java
  src/main/java/org/noostak/group/application/GroupService.java
  src/main/java/org/noostak/group/application/InvitationCodeGenerator.java
  src/main/java/org/noostak/group/common/exception/GroupErrorCode.java
  src/main/java/org/noostak/group/common/success/GroupSuccessCode.java
  src/main/java/org/noostak/group/common/success/temp
  src/main/java/org/noostak/group/config/InviteCodeGeneratorConfig.java
  src/main/java/org/noostak/group/domain/DefaultInvitationCodePolicy.java
  src/main/java/org/noostak/group/domain/Group.java
  src/main/java/org/noostak/group/domain/GroupRepository.java
  src/main/java/org/noostak/group/domain/InvitationCodePolicy.java
  src/main/java/org/noostak/group/dto/request/GroupCreateRequest.java
  src/main/java/org/noostak/group/dto/response/GroupCreateInternalResponse.java
  src/main/java/org/noostak/group/dto/response/GroupCreateResponse.java
  src/main/java/org/noostak/group/dto/temp
  src/main/java/org/noostak/infra/KeyAndUrl.java
  src/main/java/org/noostak/infra/S3Storage.java
  src/main/java/org/noostak/infra/S3StorageImpl.java
  src/main/java/org/noostak/member/domain/Member.java
  src/main/java/org/noostak/member/domain/MemberRepository.java
  src/main/java/org/noostak/member/domain/vo/MemberProfileImageKey.java
  src/main/java/org/noostak/membergroup/domain/MemberGroups.java
  src/test/java/org/noostak/NoostakApplicationTests.java
  src/test/java/org/noostak/group/application/GroupCreateServiceImplTest.java
  src/test/java/org/noostak/group/domain/GroupRepositoryTest.java
  src/test/java/org/noostak/infra/FakeS3StorageImpl.java
  src/test/java/org/noostak/infra/S3ServiceTest.java
  src/test/java/org/noostak/member/MemberRepositoryTest.java
  src/test/java/org/noostak/member/domain/vo/AuthIdTest.java
  src/test/java/org/noostak/member/domain/vo/MemberNameTest.java
  src/test/java/org/noostak/member/domain/vo/MemberProfileImageKeyTest.java
Labels: ✨ feat, 🐋 장순 🐋

#58 [✨ feat] 그룹 정보 보기 API 구현
  build.gradle
  src/main/java/org/noostak/global/config/QueryDslConfig.java
  src/main/java/org/noostak/group/api/GroupController.java
  src/main/java/org/noostak/group/application/GroupCreateService.java
  src/main/java/org/noostak/group/application/GroupCreateServiceImpl.java
  src/main/java/org/noostak/group/application/GroupInfoService.java
  src/main/java/org/noostak/group/application/GroupInfoServiceImpl.java
  src/main/java/org/noostak/group/application/GroupRetrieveService.java
  src/main/java/org/noostak/group/application/GroupRetrieveServiceImpl.java
  src/main/java/org/noostak/group/application/GroupService.java
  src/main/java/org/noostak/group/common/exception/GroupErrorCode.java
  src/main/java/org/noostak/group/common/success/GroupSuccessCode.java
  src/main/java/org/noostak/group/dto/response/create/GroupCreateInternalResponse.java
  src/main/java/org/noostak/group/dto/response/create/GroupCreateResponse.java
  src/main/java/org/noostak/group/dto/response/info/GroupInfoResponse.java
  src/main/java/org/noostak/group/dto/response/info/GroupMemberInfoResponse.java
  src/main/java/org/noostak/group/dto/response/info/GroupSummaryResponse.java
  src/main/java/org/noostak/group/dto/response/retrieve/GroupInternalRetrieveResponse.java
  src/main/java/org/noostak/group/dto/response/retrieve/GroupRetrieveResponse.java
  src/main/java/org/noostak/group/dto/response/retrieve/GroupsRetrieveResponse.java
  src/main/java/org/noostak/membergroup/domain/MemberGroupRepository.java
  src/main/java/org/noostak/membergroup/domain/MemberGroupRepositoryCustom.java
  src/main/java/org/noostak/membergroup/domain/MemberGroupRepositoryImpl.java
  src/test/java/org/noostak/group/application/GroupCreateServiceImplTest.java
  src/test/java/org/noostak/group/application/GroupInfoServiceImplTest.java
  src/test/java/org/noostak/group/application/GroupRetrieveServiceImplTest.java
  src/test/java/org/noostak/membergroup/MemberGroupRepositoryTest.java
Labels: ✨ feat, 🐋 장순 🐋

#60 [✨ feat] 약속 생성 API 구현
  src/main/java/org/noostak/appointment/api/AppointmentController.java
  src/main/java/org/noostak/appointment/api/temp
  src/main/java/org/noostak/appointment/application/AppointmentCreateService.java
  src/main/java/org/noostak/appointment/application/AppointmentCreateServiceImpl.java
  src/main/java/org/noostak/appointment/application/AppointmentService.java
  src/main/java/org/noostak/appointment/application/temp
  src/main/java/org/noostak/appointment/common/exception/AppointmentErrorCode.java
  src/main/java/org/noostak/appointment/common/success/AppointmentSuccessCode.java
  src/main/java/org/noostak/appointment/common/success/temp
  src/main/java/org/noostak/appointment/domain/Appointment.java
  src/main/java/org/noostak/appointment/domain/AppointmentHostSelectionTimes.java
  src/main/java/org/noostak/appointment/domain/AppointmentRepository.java
  src/main/java/org/noostak/appointment/domain/vo/AppointmentCategory.java
  src/main/java/org/noostak/appointment/dto/request/AppointmentCreateRequest.java
  src/main/java/org/noostak/appointment/dto/temp
  src/main/java/org/noostak/group/application/GroupInfoServiceImpl.java
  src/main/java/org/noostak/group/application/GroupRetrieveServiceImpl.java
  src/main/java/org/noostak/membergroup/domain/MemberGroupRepositoryCustom.java
  src/main/java/org/noostak/membergroup/domain/MemberGroupRepositoryImpl.java
  src/test/java/org/noostak/appointment/application/AppointmentCreateServiceImplTest.java
  src/test/java/org/noostak/appointment/domain/AppointmentRepositoryTest.java
  src/test/java/org/noostak/appointment/domain/vo/AppointmentCategoryTest.java
  src/test/java/org/noostak/membergroup/MemberGroupRepositoryTest.java
Labels: ✨ feat, 🐋 장순 🐋

#65 [✨ feat] 약속 가능 시간 조회 API 구현
  src/main/java/org/noostak/NoostakApplication.java
  src/main/java/org/noostak/appointment/application/AppointmentCreateServiceImpl.java
  src/main/java/org/noostak/appointment/domain/AppointmentHostSelectionTime.java
  src/main/java/org/noostak/appointment/domain/AppointmentHostSelectionTimeRepository.java
  src/main/java/org/noostak/appointment/dto/request/AppointmentCreateRequest.java
  src/main/java/org/noostak/appointment/dto/request/AppointmentHostSelectionTimeRequest.java
  src/main/java/org/noostak/appointmentmember/api/AppointmentMemberController.java
  src/main/java/org/noostak/appointmentmember/application/AppointmentMemberRetrieveAvailableTimesService.java
  src/main/java/org/noostak/appointmentmember/application/AppointmentMemberRetrieveAvailableTimesServiceImpl.java
  src/main/java/org/noostak/appointmentmember/application/AppointmentMemberSaveAvailableTimesService.java
  src/main/java/org/noostak/appointmentmember/application/AppointmentMemberSaveAvailableTimesServiceImpl.java
  src/main/java/org/noostak/appointmentmember/application/AppointmentSaveAvailableTimesService.java
  src/main/java/org/noostak/appointmentmember/application/AppointmentSaveAvailableTimesServiceImpl.java
  src/main/java/org/noostak/appointmentmember/common/success/AppointmentMemberSuccessCode.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMember.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberAvailableTime.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberAvailableTimesRepository.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberRepository.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberRepositoryCustom.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberRepositoryImpl.java
  src/main/java/org/noostak/appointmentmember/domain/repository/AppointmentMemberAvailableTimesRepository.java
  src/main/java/org/noostak/appointmentmember/domain/repository/AppointmentMemberRepositoryImpl.java
  src/main/java/org/noostak/appointmentmember/dto/request/AppointmentMemberAvailableTimeRequest.java
  src/main/java/org/noostak/appointmentmember/dto/request/AppointmentMemberAvailableTimesRequest.java
  src/main/java/org/noostak/appointmentmember/dto/request/AvailableTimeRequest.java
  src/main/java/org/noostak/appointmentmember/dto/request/AvailableTimesRequest.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentHostSelectionTimeResponse.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentHostSelectionTimesResponse.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentMemberAvailableTimeResponse.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentMemberAvailableTimesResponse.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentMemberInfoResponse.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentMembersAvailableTimesResponse.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentScheduleResponse.java
  src/test/java/org/noostak/appointment/application/AppointmentCreateServiceImplTest.java
  src/test/java/org/noostak/appointment/domain/AppointmentHostSelectionTimeRepositoryTest.java
  src/test/java/org/noostak/appointmentmember/application/AppointmentMemberRetrieveAvailableTimesServiceImplTest.java
  src/test/java/org/noostak/appointmentmember/application/AppointmentMemberSaveAvailableTimesServiceImplTest.java
  src/test/java/org/noostak/appointmentmember/domain/repository/AppointmentMemberAvailableTimesRepositoryTest.java
  src/test/java/org/noostak/appointmentmember/domain/repository/AppointmentMemberRepositoryTest.java
  src/test/java/org/noostak/group/application/GroupCreateServiceImplTest.java
  src/test/java/org/noostak/group/application/GroupInfoServiceImplTest.java
  src/test/java/org/noostak/group/application/GroupRetrieveServiceImplTest.java
  src/test/java/org/noostak/group/domain/GroupRepositoryTest.java
Labels: ✨ feat, 🐋 장순 🐋

#89 [✨ feat] 추천된 약속 조회 API 구현
  src/main/java/org/noostak/appointment/api/AppointmentController.java
  src/main/java/org/noostak/appointment/application/AppointmentService.java
  src/main/java/org/noostak/appointment/application/create/AppointmentCreateService.java
  src/main/java/org/noostak/appointment/application/create/AppointmentCreateServiceImpl.java
  src/main/java/org/noostak/appointment/application/recommendation/AppointmentHostSelectedTimeQueryService.java
  src/main/java/org/noostak/appointment/application/recommendation/AppointmentMemberAvailabilityQueryService.java
  src/main/java/org/noostak/appointment/application/recommendation/AppointmentOptionCommandService.java
  src/main/java/org/noostak/appointment/application/recommendation/AppointmentOptionPriorityService.java
  src/main/java/org/noostak/appointment/application/recommendation/AppointmentParticipantQueryService.java
  src/main/java/org/noostak/appointment/application/recommendation/AppointmentRecommendationFacade.java
  src/main/java/org/noostak/appointment/application/recommendation/AppointmentRecommendedOptionService.java
  src/main/java/org/noostak/appointment/application/recommendation/AppointmentRecommendedOptionServiceImpl.java
  src/main/java/org/noostak/appointment/common/exception/AppointmentErrorCode.java
  src/main/java/org/noostak/appointment/dto/response/AppointmentMyInfoResponse.java
  src/main/java/org/noostak/appointment/dto/response/AppointmentOptionAvailabilityResponse.java
  src/main/java/org/noostak/appointment/dto/response/AppointmentOptionResponse.java
  src/main/java/org/noostak/appointment/dto/response/AppointmentOptionTimeResponse.java
  src/main/java/org/noostak/appointment/dto/response/AppointmentPriorityGroupResponse.java
  src/main/java/org/noostak/appointment/dto/response/AppointmentRecommendedOptionsResponse.java
  src/main/java/org/noostak/appointment/dto/response/AvailableFriendsResponse.java
  src/main/java/org/noostak/appointment/dto/response/UnavailableFriendsResponse.java
  src/main/java/org/noostak/appointment/util/AppointmentAvailabilityMatcher.java
  src/main/java/org/noostak/appointment/util/AppointmentOptionResponseMapper.java
  src/main/java/org/noostak/appointment/util/AppointmentOptionSorter.java
  src/main/java/org/noostak/appointment/util/AppointmentTimeSplitter.java
  src/main/java/org/noostak/appointment/util/TimeSlot.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberAvailableTimesRepository.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberRepository.java
  src/main/java/org/noostak/likes/domain/Like.java
  src/main/java/org/noostak/likes/domain/LikeRepository.java
  src/test/java/org/noostak/appointment/application/AppointmentCreateServiceImplTest.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentHostSelectedTimeQueryServiceTest.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentMemberAvailabilityQueryServiceTest.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentOptionCommandServiceTest.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentOptionPriorityServiceTest.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentParticipantQueryServiceTest.java
  src/test/java/org/noostak/appointmentmember/domain/repository/AppointmentMemberAvailableTimesRepositoryTest.java
  src/test/java/org/noostak/appointmentmember/domain/repository/AppointmentMemberRepositoryTest.java
  src/test/java/org/noostak/appointmentoption/domain/AppointmentOptionRepositoryTest.java
  src/test/java/org/noostak/likes/domain/LikeRepositoryTest.java
Labels: ✨ feat, 🐋 장순 🐋

#86 [✨feat] 특정 옵션 좋아요 추가
  src/main/java/org/noostak/appointment/domain/AppointmentRepository.java
  src/main/java/org/noostak/appointment/util/AppointmentOptionResponseMapper.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOptionRepository.java
  src/main/java/org/noostak/likes/api/LikeController.java
  src/main/java/org/noostak/likes/api/temp
  src/main/java/org/noostak/likes/application/LikeService.java
  src/main/java/org/noostak/likes/application/LikeServiceImpl.java
  src/main/java/org/noostak/likes/application/temp
  src/main/java/org/noostak/likes/common/LikesException.java
  src/main/java/org/noostak/likes/common/exception/LikesErrorCode.java
  src/main/java/org/noostak/likes/common/exception/LikesException.java
  src/main/java/org/noostak/likes/common/success/LikesSuccessCode.java
  src/main/java/org/noostak/likes/domain/Like.java
  src/main/java/org/noostak/likes/domain/LikeRepository.java
  src/main/java/org/noostak/likes/domain/vo/LikesCount.java
  src/main/java/org/noostak/likes/dto/IncreaseResponse.java
  src/main/java/org/noostak/likes/dto/temp
  src/main/java/org/noostak/member/common/MemberErrorCode.java
  src/main/java/org/noostak/member/domain/MemberRepository.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentOptionPriorityServiceTest.java
  src/test/java/org/noostak/likes/domain/LikeServiceImplTest.java
  src/test/java/org/noostak/likes/domain/vo/LikesCountTest.java
Labels: ✨ feat, 🦖 용태 🦖

#92 [✨ feat] 캘린더 - 약속 정보 가져오기 구현
  src/main/java/org/noostak/appointment/api/CalendarController.java
  src/main/java/org/noostak/appointment/application/CalendarService.java
  src/main/java/org/noostak/appointment/application/CalendarServiceImpl.java
  src/main/java/org/noostak/appointment/common/success/CalendarSuccessCode.java
  src/main/java/org/noostak/appointment/domain/AppointmentRepository.java
  src/main/java/org/noostak/appointment/dto/calendar/CalendarResponse.java
  src/main/java/org/noostak/appointment/dto/calendar/MonthAppointment.java
  src/main/java/org/noostak/appointment/dto/calendar/MonthAppointments.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOption.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOptionRepository.java
  src/test/java/org/noostak/appointment/application/CalendarServiceImplTest.java
  src/test/java/org/noostak/appointment/domain/AppointmentRepositoryTest.java
  src/test/java/org/noostak/appointmentoption/domain/AppointmentOptionRepositoryTest.java
Labels: ✨ feat, 🦖 용태 🦖

#97 [✨feat] 마이페이지 - 내 정보 보기
  src/main/java/org/noostak/auth/domain/vo/AuthId.java
  src/main/java/org/noostak/auth/domain/vo/Code.java
  src/main/java/org/noostak/member/api/MemberController.java
  src/main/java/org/noostak/member/application/MemberService.java
  src/main/java/org/noostak/member/application/MemberServiceImpl.java
  src/main/java/org/noostak/member/common/exception/MemberErrorCode.java
  src/main/java/org/noostak/member/common/exception/MemberException.java
  src/main/java/org/noostak/member/common/success/MemberSuccessCode.java
  src/main/java/org/noostak/member/domain/MemberRepository.java
  src/main/java/org/noostak/member/domain/vo/MemberName.java
  src/main/java/org/noostak/member/domain/vo/MemberProfileImageKey.java
  src/main/java/org/noostak/member/dto/GetProfileResponse.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentHostSelectedTimeQueryServiceImplTest.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentMemberAvailabilityQueryServiceTest.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentOptionCommandServiceTest.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentParticipantQueryServiceTest.java
  src/test/java/org/noostak/group/application/ongoing/GroupOngoingAppointmentServiceImplTest.java
  src/test/java/org/noostak/likes/domain/LikeRepositoryTest.java
  src/test/java/org/noostak/member/domain/MemberServiceImplTest.java
  src/test/java/org/noostak/member/domain/vo/AuthIdTest.java
  src/test/java/org/noostak/member/domain/vo/MemberNameTest.java
  src/test/java/org/noostak/member/domain/vo/MemberProfileImageKeyTest.java
Labels: ✨ feat, 🦖 용태 🦖

#108 [✨feat] 확정된 약속들 조회 API 구현
  src/main/java/org/noostak/appointment/application/CalendarServiceImpl.java
  src/main/java/org/noostak/appointment/common/exception/AppointmentErrorCode.java
  src/main/java/org/noostak/appointment/common/success/AppointmentSuccessCode.java
  src/main/java/org/noostak/appointment/domain/AppointmentRepository.java
  src/main/java/org/noostak/appointment/domain/AppointmentRepositoryCustom.java
  src/main/java/org/noostak/appointment/domain/AppointmentRepositoryImpl.java
  src/main/java/org/noostak/appointment/domain/vo/AppointmentCategory.java
  src/main/java/org/noostak/appointmentoption/api/AppointmentOptionController.java
  src/main/java/org/noostak/appointmentoption/application/AppointmentOptionConfirmedOptionServiceImpl.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOptionRepository.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOptionRepositoryCustom.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOptionRepositoryImpl.java
  src/main/java/org/noostak/group/api/GroupController.java
  src/main/java/org/noostak/group/application/GroupService.java
  src/main/java/org/noostak/group/application/confirmed/GroupConfirmedAppointmentsService.java
  src/main/java/org/noostak/group/application/confirmed/GroupConfirmedAppointmentsServiceImpl.java
  src/main/java/org/noostak/group/application/create/GroupCreateService.java
  src/main/java/org/noostak/group/application/create/GroupCreateServiceImpl.java
  src/main/java/org/noostak/group/application/info/GroupInfoService.java
  src/main/java/org/noostak/group/application/info/GroupInfoServiceImpl.java
  src/main/java/org/noostak/group/application/retrieve/GroupRetrieveService.java
  src/main/java/org/noostak/group/application/retrieve/GroupRetrieveServiceImpl.java
  src/main/java/org/noostak/group/common/exception/GroupErrorCode.java
  src/main/java/org/noostak/group/common/success/GroupSuccessCode.java
  src/main/java/org/noostak/group/dto/response/confirmed/AppointmentTimeResponse.java
  src/main/java/org/noostak/group/dto/response/confirmed/ConfirmedAppointmentsResponse.java
  src/main/java/org/noostak/group/dto/response/confirmed/GroupConfirmedAppointmentsResponse.java
  src/main/java/org/noostak/group/dto/response/confirmed/GroupConfirmedInfoResponse.java
  src/main/java/org/noostak/group/util/GroupConfirmedResponseMapper.java
  src/main/java/org/noostak/member/application/MemberServiceImpl.java
  src/main/java/org/noostak/member/domain/MemberRepository.java
  src/main/java/org/noostak/member/domain/vo/MemberName.java
  src/test/java/org/noostak/appointment/application/CalendarServiceImplTest.java
  src/test/java/org/noostak/appointment/domain/AppointmentRepositoryTest.java
  src/test/java/org/noostak/appointment/domain/vo/AppointmentCategoryTest.java
  src/test/java/org/noostak/appointmentoption/domain/AppointmentOptionRepositoryTest.java
  src/test/java/org/noostak/group/application/GroupCreateServiceImplTest.java
  src/test/java/org/noostak/group/application/GroupInfoServiceImplTest.java
  src/test/java/org/noostak/group/application/GroupRetrieveServiceImplTest.java
  src/test/java/org/noostak/group/application/confirmed/GroupConfirmedAppointmentsServiceImplTest.java
  src/test/java/org/noostak/member/domain/MemberServiceImplTest.java
Labels: ✨ feat, 🐋 장순 🐋

#113 [🧬 merge] develop -> staging
  .github/workflows/DOCKER-CD-STAGING.yml
Labels: 🧬 merge, 🦖 용태 🦖

#117 [✨feat] 그룹 상세 - 그룹 코드 입력하기
  src/main/java/org/noostak/group/api/GroupController.java
  src/main/java/org/noostak/group/application/GroupJoinService.java
  src/main/java/org/noostak/group/application/GroupJoinServiceImpl.java
  src/main/java/org/noostak/group/application/GroupService.java
  src/main/java/org/noostak/group/common/exception/GroupErrorCode.java
  src/main/java/org/noostak/group/common/success/GroupSuccessCode.java
  src/main/java/org/noostak/group/domain/GroupRepository.java
  src/main/java/org/noostak/group/dto/request/GroupJoinRequest.java
  src/main/java/org/noostak/group/dto/response/GroupJoinResponse.java
  src/test/java/org/noostak/group/application/GroupJoinServiceImplTest.java
  src/test/java/org/noostak/group/domain/GroupRepositoryTest.java
Labels: ✨ feat, 🦖 용태 🦖

#118 [✨feat] 캘린더 정보 보기 - 응답에 category 필드 추가
  src/main/java/org/noostak/appointment/dto/calendar/MonthAppointment.java
  src/main/java/org/noostak/auth/dto/KakaoAccessTokenResponse.java
Labels: ✨ feat, 🦖 용태 🦖
