Repository Noostak/Noostak-Server, pull requests merged in 2025-04, with the labels that each got.

#200 [♻️refactor] 회원 정보 수정 api 변경 및 enum 활용 DTO 필드 수정
  src/main/java/org/noostak/appointmentoption/util/AppointmentOptionConfirmedOptionConverter.java
  src/main/java/org/noostak/member/api/MemberController.java
  src/main/java/org/noostak/member/application/MemberService.java
  src/main/java/org/noostak/member/application/MemberServiceImpl.java
  src/main/java/org/noostak/member/dto/UpdateProfileRequest.java
Labels: ♻️ refactor, 🦖 용태 🦖

#201 [🧬 merge] develop -> staging
  src/main/java/org/noostak/appointmentoption/util/AppointmentOptionConfirmedOptionConverter.java
  src/main/java/org/noostak/member/api/MemberController.java
  src/main/java/org/noostak/member/application/MemberService.java
  src/main/java/org/noostak/member/application/MemberServiceImpl.java
  src/main/java/org/noostak/member/dto/UpdateProfileRequest.java
Labels: 🧬 merge, 🦖 용태 🦖

#204 [♻️ refactor] 약속 추천 - 확정된 약속 조회 API 개선
  src/main/java/org/noostak/appointment/common/success/AppointmentSuccessCode.java
  src/main/java/org/noostak/appointmentoption/api/AppointmentOptionController.java
  src/main/java/org/noostak/appointmentoption/application/info/AppointmentOptionInfoService.java
  src/main/java/org/noostak/appointmentoption/application/info/AppointmentOptionInfoServiceImpl.java
  src/main/java/org/noostak/appointmentoption/application/info/AppointmentOptionService.java
  src/main/java/org/noostak/appointmentoption/dto/response/info/AppointmentOptionInfoAvailableFriendsResponse.java
  src/main/java/org/noostak/appointmentoption/dto/response/info/AppointmentOptionInfoMyInfoResponse.java
  src/main/java/org/noostak/appointmentoption/dto/response/info/AppointmentOptionInfoResponse.java
  src/main/java/org/noostak/appointmentoption/dto/response/info/AppointmentOptionInfoTimeResponse.java
  src/main/java/org/noostak/appointmentoption/dto/response/info/AppointmentOptionInfoUnavailableFriendsResponse.java
  src/main/java/org/noostak/appointmentoption/util/AppointmentOptionInfoOptionConverter.java
Labels: ♻️ refactor, 🐋 장순 🐋

#205 [🧬 merge] develop -> staging
  src/main/java/org/noostak/appointment/common/success/AppointmentSuccessCode.java
  src/main/java/org/noostak/appointmentoption/api/AppointmentOptionController.java
  src/main/java/org/noostak/appointmentoption/application/info/AppointmentOptionInfoService.java
  src/main/java/org/noostak/appointmentoption/application/info/AppointmentOptionInfoServiceImpl.java
  src/main/java/org/noostak/appointmentoption/application/info/AppointmentOptionService.java
  src/main/java/org/noostak/appointmentoption/dto/response/info/AppointmentOptionInfoAvailableFriendsResponse.java
  src/main/java/org/noostak/appointmentoption/dto/response/info/AppointmentOptionInfoMyInfoResponse.java
  src/main/java/org/noostak/appointmentoption/dto/response/info/AppointmentOptionInfoResponse.java
  src/main/java/org/noostak/appointmentoption/dto/response/info/AppointmentOptionInfoTimeResponse.java
  src/main/java/org/noostak/appointmentoption/dto/response/info/AppointmentOptionInfoUnavailableFriendsResponse.java
  src/main/java/org/noostak/appointmentoption/util/AppointmentOptionInfoOptionConverter.java
Labels: 🐋 장순 🐋, 🧬 merge

#207 [♻️ refactor] 약속 이름 검증 개선
  src/main/java/org/noostak/appointment/common/exception/AppointmentErrorCode.java
  src/main/java/org/noostak/appointment/domain/vo/AppointmentName.java
  src/test/java/org/noostak/appointment/domain/vo/AppointmentNameTest.java
Labels: ♻️ refactor, 🐋 장순 🐋

#208 [🧬 merge] develop -> staging
  src/main/java/org/noostak/appointment/common/exception/AppointmentErrorCode.java
  src/main/java/org/noostak/appointment/domain/vo/AppointmentName.java
  src/test/java/org/noostak/appointment/domain/vo/AppointmentNameTest.java
Labels: 🐋 장순 🐋, 🧬 merge

#210 [🔧 fix ] 약속 옵션 조회 방식 수정
  src/main/java/org/noostak/appointment/api/AppointmentController.java
  src/main/java/org/noostak/appointment/common/success/AppointmentSuccessCode.java
  src/main/java/org/noostak/appointmentmember/domain/vo/AppointmentAvailability.java
  src/main/java/org/noostak/appointmentoption/application/AppointmentOptionConfirmServiceImpl.java
  src/main/java/org/noostak/appointmentoption/application/info/AppointmentOptionInfoServiceImpl.java
  src/main/java/org/noostak/appointmentoption/domain/vo/AppointmentOptionStatus.java
Labels: 🐋 장순 🐋, 🔧 fix

#211 [🧬 merge] develop -> staging
  src/main/java/org/noostak/appointment/api/AppointmentController.java
  src/main/java/org/noostak/appointment/common/success/AppointmentSuccessCode.java
  src/main/java/org/noostak/appointmentmember/domain/vo/AppointmentAvailability.java
  src/main/java/org/noostak/appointmentoption/application/AppointmentOptionConfirmServiceImpl.java
  src/main/java/org/noostak/appointmentoption/application/info/AppointmentOptionInfoServiceImpl.java
  src/main/java/org/noostak/appointmentoption/domain/vo/AppointmentOptionStatus.java
Labels: 🐋 장순 🐋, 🧬 merge

#214 [♻️ refactor] 약속 옵션 조회 관련 로직 수정
  src/main/java/org/noostak/appointment/util/AppointmentOptionResponseMapper.java
  src/main/java/org/noostak/appointmentmember/application/AppointmentMemberSaveServiceImpl.java
  src/main/java/org/noostak/appointmentmember/domain/vo/AppointmentAvailability.java
  src/main/java/org/noostak/appointmentoption/application/info/AppointmentOptionInfoServiceImpl.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOptionRepository.java
  src/main/java/org/noostak/appointmentoption/util/AppointmentOptionInfoOptionConverter.java
Labels: ♻️ refactor, 🦖 용태 🦖

#215 [🧬 merge] develop -> staging
  src/main/java/org/noostak/appointment/util/AppointmentOptionResponseMapper.java
  src/main/java/org/noostak/appointmentmember/application/AppointmentMemberSaveServiceImpl.java
  src/main/java/org/noostak/appointmentmember/domain/vo/AppointmentAvailability.java
  src/main/java/org/noostak/appointmentoption/application/info/AppointmentOptionInfoServiceImpl.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOptionRepository.java
  src/main/java/org/noostak/appointmentoption/util/AppointmentOptionInfoOptionConverter.java
Labels: 🧬 merge, 🦖 용태 🦖

#216 [♻️ refactor] 약속 옵션이 항상 같은 순서로 추천되도록 수정
  src/main/java/org/noostak/appointment/application/recommendation/impl/AppointmentOptionPriorityServiceImpl.java
  src/main/java/org/noostak/appointment/util/AppointmentOptionSorter.java
  src/main/java/org/noostak/group/application/GroupJoinServiceImpl.java
  src/main/java/org/noostak/group/domain/Group.java
  src/main/java/org/noostak/membergroup/domain/MemberGroupRepository.java
Labels: ♻️ refactor, 🐋 장순 🐋, 🦖 용태 🦖

#217 [🧬 merge] develop -> staging
  src/main/java/org/noostak/appointment/application/recommendation/impl/AppointmentOptionPriorityServiceImpl.java
  src/main/java/org/noostak/appointment/util/AppointmentOptionSorter.java
  src/main/java/org/noostak/group/application/GroupJoinServiceImpl.java
  src/main/java/org/noostak/group/domain/Group.java
  src/main/java/org/noostak/membergroup/domain/MemberGroupRepository.java
Labels: 🐋 장순 🐋, 🧬 merge, 🦖 용태 🦖

#219 [♻️ refactor] LikeController를 약속 도메인 하위로 이동
  src/main/java/org/noostak/appointment/api/LikeController.java
  src/main/java/org/noostak/appointment/application/recommendation/impl/AppointmentOptionPriorityServiceImpl.java
  src/main/java/org/noostak/appointment/util/AppointmentOptionResponseMapper.java
  src/main/java/org/noostak/auth/application/AuthInfoServiceImpl.java
  src/main/java/org/noostak/like/application/LikeService.java
  src/main/java/org/noostak/like/application/LikeServiceImpl.java
  src/main/java/org/noostak/like/common/exception/LikesErrorCode.java
  src/main/java/org/noostak/like/common/exception/LikesException.java
  src/main/java/org/noostak/like/common/success/LikesSuccessCode.java
  src/main/java/org/noostak/like/domain/Like.java
  src/main/java/org/noostak/like/domain/LikeRepository.java
  src/main/java/org/noostak/like/domain/LikeRepositoryCustom.java
  src/main/java/org/noostak/like/domain/LikeRepositoryImpl.java
  src/main/java/org/noostak/like/dto/DecreaseResponse.java
  src/main/java/org/noostak/like/dto/IncreaseResponse.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentOptionPriorityServiceTest.java
  src/test/java/org/noostak/like/domain/LikeRepositoryTest.java
  src/test/java/org/noostak/like/domain/LikeServiceImplTest.java
Labels: ♻️ refactor, 🐋 장순 🐋

#223 [🧬 merge] : develop -> staging
  src/main/java/org/noostak/appointment/api/LikeController.java
  src/main/java/org/noostak/appointment/application/recommendation/AppointmentRecommendationFacade.java
  src/main/java/org/noostak/appointment/application/recommendation/impl/AppointmentOptionPriorityServiceImpl.java
  src/main/java/org/noostak/appointment/domain/AppointmentHostSelectionTime.java
  src/main/java/org/noostak/appointment/util/AppointmentAvailabilityMatcher.java
  src/main/java/org/noostak/appointment/util/AppointmentOptionResponseMapper.java
  src/main/java/org/noostak/appointment/util/AppointmentTimeSplitter.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberAvailableTime.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOption.java
  src/main/java/org/noostak/auth/application/AuthInfoServiceImpl.java
  src/main/java/org/noostak/global/error/core/TimeEntityErrorCode.java
  src/main/java/org/noostak/global/error/core/TimeEntityException.java
  src/main/java/org/noostak/global/utils/TimeEntity.java
  src/main/java/org/noostak/like/application/LikeService.java
  src/main/java/org/noostak/like/application/LikeServiceImpl.java
  src/main/java/org/noostak/like/common/exception/LikesErrorCode.java
  src/main/java/org/noostak/like/common/exception/LikesException.java
  src/main/java/org/noostak/like/common/success/LikesSuccessCode.java
  src/main/java/org/noostak/like/domain/Like.java
  src/main/java/org/noostak/like/domain/LikeRepository.java
  src/main/java/org/noostak/like/domain/LikeRepositoryCustom.java
  src/main/java/org/noostak/like/domain/LikeRepositoryImpl.java
  src/main/java/org/noostak/like/dto/DecreaseResponse.java
  src/main/java/org/noostak/like/dto/IncreaseResponse.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentHostSelectedTimeQueryServiceImplTest.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentOptionPriorityServiceTest.java
  src/test/java/org/noostak/like/domain/LikeRepositoryTest.java
  src/test/java/org/noostak/like/domain/LikeServiceImplTest.java
  src/test/java/org/noostak/membergroup/MemberGroupRepositoryTest.java
Labels: 🧬 merge, 🦖 용태 🦖

#226 [🧬 merge] : develop -> staging
  src/main/java/org/noostak/appointment/application/CalendarServiceImpl.java
  src/main/java/org/noostak/appointment/domain/AppointmentHostSelectionTime.java
  src/main/java/org/noostak/appointment/dto/calendar/MonthAppointment.java
  src/main/java/org/noostak/appointment/util/AppointmentAvailabilityMatcher.java
  src/main/java/org/noostak/appointment/util/TimeSlot.java
  src/main/java/org/noostak/appointmentmember/application/AppointmentMemberRetrieveAvailableTimesServiceImpl.java
  src/main/java/org/noostak/appointmentmember/application/AppointmentMemberSaveAvailableTimesServiceImpl.java
  src/main/java/org/noostak/appointmentmember/common/exception/AppointmentMemberErrorCode.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberAvailableTime.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentScheduleResponse.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOption.java
  src/main/java/org/noostak/global/utils/TimeInterval.java
Labels: 🧬 merge, 🦖 용태 🦖

#229 [🧬 merge] : develop -> staging
  src/main/java/org/noostak/appointmentmember/application/AppointmentMemberSaveAvailableTimesServiceImpl.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMember.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentParticipantQueryServiceTest.java
  src/test/java/org/noostak/appointmentmember/application/AppointmentMemberRetrieveAvailableTimesServiceImplTest.java
Labels: 🧬 merge, 🦖 용태 🦖

#231 [✨ feat] 연속적인 시간 입력을 합치는 기능 추가
  src/main/java/org/noostak/appointmentmember/application/AppointmentMemberSaveAvailableTimesServiceImpl.java
  src/main/java/org/noostak/appointmentmember/dto/request/AppointmentMemberAvailableTimesRequest.java
  src/test/java/org/noostak/appointmentmember/application/AppointmentMemberSaveAvailableTimesServiceImplTest.java
Labels: ✨ feat, 🦖 용태 🦖

#232 [🧬 merge] : develop -> staging
  src/main/java/org/noostak/appointmentmember/application/AppointmentMemberSaveAvailableTimesServiceImpl.java
  src/main/java/org/noostak/appointmentmember/dto/request/AppointmentMemberAvailableTimesRequest.java
  src/test/java/org/noostak/appointmentmember/application/AppointmentMemberSaveAvailableTimesServiceImplTest.java
Labels: 🧬 merge, 🦖 용태 🦖
