Repository Noostak/Noostak-Server, pull requests merged in 2025-03, with the labels that each got.

#120 [✨feat] JWT 인터셉터 구현
  src/main/java/org/noostak/appointment/api/AppointmentController.java
  src/main/java/org/noostak/appointmentmember/api/AppointmentMemberController.java
  src/main/java/org/noostak/global/config/JwtInterceptor.java
  src/main/java/org/noostak/group/api/GroupController.java
  src/main/java/org/noostak/likes/api/LikeController.java
Labels: ✨ feat, 🦖 용태 🦖

#121 [🧬merge] staging -> develop
  src/main/java/org/noostak/appointment/api/AppointmentController.java
  src/main/java/org/noostak/appointment/dto/calendar/MonthAppointment.java
  src/main/java/org/noostak/appointmentmember/api/AppointmentMemberController.java
  src/main/java/org/noostak/auth/application/RestClient.java
  src/main/java/org/noostak/auth/dto/AuthorizeResponse.java
  src/main/java/org/noostak/auth/dto/GoogleAccessTokenResponse.java
  src/main/java/org/noostak/auth/dto/GoogleTokenRequest.java
  src/main/java/org/noostak/auth/dto/GoogleUnlinkResponse.java
  src/main/java/org/noostak/auth/dto/GoogleUserInfoResponse.java
  src/main/java/org/noostak/auth/dto/KakaoAccessTokenResponse.java
  src/main/java/org/noostak/auth/dto/KakaoLogoutResponse.java
  src/main/java/org/noostak/auth/dto/KakaoTokenInfoResponse.java
  src/main/java/org/noostak/auth/dto/KakaoTokenResponse.java
  src/main/java/org/noostak/auth/dto/KakaoUnlinkResponse.java
  src/main/java/org/noostak/auth/dto/KakaoUserInfoResponse.java
  src/main/java/org/noostak/auth/dto/SignInRequest.java
  src/main/java/org/noostak/auth/dto/SignInResponse.java
  src/main/java/org/noostak/auth/dto/SignUpRequest.java
  src/main/java/org/noostak/auth/dto/SignUpResponse.java
  src/main/java/org/noostak/auth/dto/SocialLoginRequest.java
  src/main/java/org/noostak/auth/dto/SocialLoginResponse.java
  src/main/java/org/noostak/auth/dto/TokenResponse.java
  src/main/java/org/noostak/global/config/JwtInterceptor.java
  src/main/java/org/noostak/global/utils/GlobalLogger.java
  src/main/java/org/noostak/group/api/GroupController.java
  src/main/java/org/noostak/group/application/GroupJoinService.java
  src/main/java/org/noostak/group/application/GroupJoinServiceImpl.java
  src/main/java/org/noostak/group/application/GroupService.java
  src/main/java/org/noostak/group/common/exception/GroupErrorCode.java
  src/main/java/org/noostak/group/common/success/GroupSuccessCode.java
  src/main/java/org/noostak/group/domain/GroupRepository.java
  src/main/java/org/noostak/group/dto/request/GroupJoinRequest.java
  src/main/java/org/noostak/group/dto/response/GroupJoinResponse.java
  src/main/java/org/noostak/likes/api/LikeController.java
  src/test/java/org/noostak/group/application/GroupJoinServiceImplTest.java
  src/test/java/org/noostak/group/domain/GroupRepositoryTest.java
Labels: 🧬 merge, 🦖 용태 🦖

#122 [🧬merge] develop -> staging
  src/main/java/org/noostak/auth/application/KakaoTokenRequestFactory.java
  src/main/java/org/noostak/global/error/core/ErrorResponse.java
  src/main/java/org/noostak/member/common/exception/MemberException.java
Labels: 🧬 merge, 🦖 용태 🦖

#114 [🧬 merge] staging -> main
  .github/workflows/DOCKER-CD-PROD.yml
  .github/workflows/DOCKER-CD-STAGING.yml
  src/main/java/org/noostak/appointment/api/AppointmentController.java
  src/main/java/org/noostak/appointment/dto/calendar/MonthAppointment.java
  src/main/java/org/noostak/appointmentmember/api/AppointmentMemberController.java
  src/main/java/org/noostak/auth/application/GoogleTokenRequestFactory.java
  src/main/java/org/noostak/auth/application/KakaoTokenRequestFactory.java
  src/main/java/org/noostak/auth/application/RestClient.java
  src/main/java/org/noostak/auth/dto/AuthorizeResponse.java
  src/main/java/org/noostak/auth/dto/GoogleAccessTokenResponse.java
  src/main/java/org/noostak/auth/dto/GoogleTokenRequest.java
  src/main/java/org/noostak/auth/dto/GoogleUnlinkResponse.java
  src/main/java/org/noostak/auth/dto/GoogleUserInfoResponse.java
  src/main/java/org/noostak/auth/dto/KakaoAccessTokenResponse.java
  src/main/java/org/noostak/auth/dto/KakaoLogoutResponse.java
  src/main/java/org/noostak/auth/dto/KakaoTokenInfoResponse.java
  src/main/java/org/noostak/auth/dto/KakaoTokenResponse.java
  src/main/java/org/noostak/auth/dto/KakaoUnlinkResponse.java
  src/main/java/org/noostak/auth/dto/KakaoUserInfoResponse.java
  src/main/java/org/noostak/auth/dto/SignInRequest.java
  src/main/java/org/noostak/auth/dto/SignInResponse.java
  src/main/java/org/noostak/auth/dto/SignUpRequest.java
  src/main/java/org/noostak/auth/dto/SignUpResponse.java
  src/main/java/org/noostak/auth/dto/SocialLoginRequest.java
  src/main/java/org/noostak/auth/dto/SocialLoginResponse.java
  src/main/java/org/noostak/auth/dto/TokenResponse.java
  src/main/java/org/noostak/global/config/JwtInterceptor.java
  src/main/java/org/noostak/global/error/core/ErrorResponse.java
  src/main/java/org/noostak/global/utils/GlobalLogger.java
  src/main/java/org/noostak/group/api/GroupController.java
  src/main/java/org/noostak/group/application/GroupJoinService.java
  src/main/java/org/noostak/group/application/GroupJoinServiceImpl.java
  src/main/java/org/noostak/group/application/GroupService.java
  src/main/java/org/noostak/group/common/exception/GroupErrorCode.java
  src/main/java/org/noostak/group/common/success/GroupSuccessCode.java
  src/main/java/org/noostak/group/domain/GroupRepository.java
  src/main/java/org/noostak/group/dto/request/GroupJoinRequest.java
  src/main/java/org/noostak/group/dto/response/GroupJoinResponse.java
  src/main/java/org/noostak/likes/api/LikeController.java
  src/main/java/org/noostak/member/application/MemberServiceImpl.java
  src/main/java/org/noostak/member/common/exception/MemberException.java
  src/test/java/org/noostak/group/application/GroupJoinServiceImplTest.java
  src/test/java/org/noostak/group/domain/GroupRepositoryTest.java
Labels: 🧬 merge, 🦖 용태 🦖

#125 [🧬 merge] develop -> staging
  .github/workflows/DOCKER-CD-PROD.yml
  .github/workflows/DOCKER-CD-STAGING.yml
  Dockerfile-prod
  Dockerfile-staging
Labels: 🧬 merge, 🦖 용태 🦖

#130 [♻️ refactor] 약속 확정 - 확정된 약속 조회 반환값 수정
  src/main/java/org/noostak/group/api/GroupController.java
Labels: ♻️ refactor, 🐋 장순 🐋

#132 [✨feat] Oauth 회원가입 로직 수정
  src/main/java/org/noostak/auth/api/OauthController.java
  src/main/java/org/noostak/auth/application/AuthInfoService.java
  src/main/java/org/noostak/auth/application/AuthInfoServiceImpl.java
  src/main/java/org/noostak/global/config/WebConfig.java
  src/main/java/org/noostak/global/error/handler/GlobalExceptionHandler.java
  src/main/java/org/noostak/infra/S3ServiceImpl.java
  src/test/java/org/noostak/auth/application/FakeAuthInfoService.java
Labels: ✨ feat, 🦖 용태 🦖

#137 [♻️ refactor] 로그 정보 추가
  src/main/java/org/noostak/global/config/JwtInterceptor.java
Labels: ♻️ refactor, 🦖 용태 🦖

#141 [♻️ refactor] 토큰 인증방식 변경
  src/main/java/org/noostak/auth/api/OauthController.java
  src/main/java/org/noostak/auth/application/AuthInfoService.java
  src/main/java/org/noostak/auth/application/AuthInfoServiceImpl.java
  src/main/java/org/noostak/auth/application/OauthService.java
  src/main/java/org/noostak/auth/application/apple/AppleServiceImpl.java
  src/main/java/org/noostak/auth/application/google/GoogleServiceImpl.java
  src/main/java/org/noostak/auth/application/jwt/JwtTokenProvider.java
  src/main/java/org/noostak/auth/application/jwt/config/JwtTokenConfig.java
  src/main/java/org/noostak/auth/application/kakao/KakaoServiceImpl.java
  src/main/java/org/noostak/auth/application/kakao/KakaoTokenRequestFactory.java
  src/main/java/org/noostak/auth/domain/AuthInfo.java
  src/main/java/org/noostak/auth/domain/AuthInfoRepository.java
  src/main/java/org/noostak/auth/dto/common/SignUpRequest.java
  src/main/java/org/noostak/auth/dto/common/TokenResponse.java
  src/main/java/org/noostak/global/config/JwtInterceptor.java
  src/main/java/org/noostak/global/success/SuccessResponse.java
  src/main/java/org/noostak/group/domain/Group.java
  src/main/java/org/noostak/infra/S3ServiceImpl.java
  src/main/java/org/noostak/member/application/MemberServiceImpl.java
  src/main/java/org/noostak/member/domain/Member.java
  src/test/java/org/noostak/auth/application/AuthInfoServiceImplTest.java
  src/test/java/org/noostak/auth/application/FakeAuthInfoService.java
  src/test/java/org/noostak/auth/domain/FakeAuthInfoRepository.java
Labels: ♻️ refactor, 🦖 용태 🦖

#142 [🧬 merge] develop -> staging
  src/main/java/org/noostak/auth/api/OauthController.java
  src/main/java/org/noostak/auth/application/AuthInfoService.java
  src/main/java/org/noostak/auth/application/AuthInfoServiceImpl.java
  src/main/java/org/noostak/auth/application/OauthService.java
  src/main/java/org/noostak/auth/application/apple/AppleServiceImpl.java
  src/main/java/org/noostak/auth/application/google/GoogleServiceImpl.java
  src/main/java/org/noostak/auth/application/jwt/JwtTokenProvider.java
  src/main/java/org/noostak/auth/application/jwt/config/JwtTokenConfig.java
  src/main/java/org/noostak/auth/application/kakao/KakaoServiceImpl.java
  src/main/java/org/noostak/auth/domain/AuthInfo.java
  src/main/java/org/noostak/auth/domain/AuthInfoRepository.java
  src/main/java/org/noostak/auth/dto/common/SignUpRequest.java
  src/main/java/org/noostak/auth/dto/common/TokenResponse.java
  src/main/java/org/noostak/global/config/JwtInterceptor.java
  src/main/java/org/noostak/global/success/SuccessResponse.java
  src/main/java/org/noostak/group/domain/Group.java
  src/main/java/org/noostak/infra/S3ServiceImpl.java
  src/main/java/org/noostak/member/domain/Member.java
  src/test/java/org/noostak/auth/application/AuthInfoServiceImplTest.java
  src/test/java/org/noostak/auth/application/FakeAuthInfoService.java
  src/test/java/org/noostak/auth/domain/FakeAuthInfoRepository.java
Labels: 🧬 merge, 🦖 용태 🦖

#144 [✨feat] 스웨거 설정 추가
  build.gradle
  src/main/java/org/noostak/appointment/api/AppointmentController.java
  src/main/java/org/noostak/appointment/api/CalendarController.java
  src/main/java/org/noostak/appointmentmember/api/AppointmentMemberController.java
  src/main/java/org/noostak/appointmentoption/api/AppointmentOptionController.java
  src/main/java/org/noostak/auth/api/AuthController.java
  src/main/java/org/noostak/global/config/HomeController.java
  src/main/java/org/noostak/global/config/swagger/AppointmentMemberSwagger.java
  src/main/java/org/noostak/global/config/swagger/AppointmentOptionSwagger.java
  src/main/java/org/noostak/global/config/swagger/AppointmentSwagger.java
  src/main/java/org/noostak/global/config/swagger/AuthSwagger.java
  src/main/java/org/noostak/global/config/swagger/CalendarSwagger.java
  src/main/java/org/noostak/global/config/swagger/GroupSwagger.java
  src/main/java/org/noostak/global/config/swagger/LikeSwagger.java
  src/main/java/org/noostak/global/config/swagger/MemberSwagger.java
  src/main/java/org/noostak/global/config/swagger/SwaggerConfig.java
  src/main/java/org/noostak/group/api/GroupController.java
  src/main/java/org/noostak/likes/api/LikeController.java
  src/main/java/org/noostak/member/api/MemberController.java
Labels: ✨ feat, 🐋 장순 🐋

#146 [🧬 merge] develop -> staging
  build.gradle
  src/main/java/org/noostak/appointment/api/AppointmentController.java
  src/main/java/org/noostak/appointment/api/CalendarController.java
  src/main/java/org/noostak/appointmentmember/api/AppointmentMemberController.java
  src/main/java/org/noostak/appointmentoption/api/AppointmentOptionController.java
  src/main/java/org/noostak/auth/api/AuthController.java
  src/main/java/org/noostak/global/config/HomeController.java
  src/main/java/org/noostak/global/config/swagger/AppointmentMemberSwagger.java
  src/main/java/org/noostak/global/config/swagger/AppointmentOptionSwagger.java
  src/main/java/org/noostak/global/config/swagger/AppointmentSwagger.java
  src/main/java/org/noostak/global/config/swagger/AuthSwagger.java
  src/main/java/org/noostak/global/config/swagger/CalendarSwagger.java
  src/main/java/org/noostak/global/config/swagger/GroupSwagger.java
  src/main/java/org/noostak/global/config/swagger/LikeSwagger.java
  src/main/java/org/noostak/global/config/swagger/MemberSwagger.java
  src/main/java/org/noostak/global/config/swagger/SwaggerConfig.java
  src/main/java/org/noostak/group/api/GroupController.java
  src/main/java/org/noostak/likes/api/LikeController.java
  src/main/java/org/noostak/member/api/MemberController.java
Labels: 🐋 장순 🐋, 🧬 merge

#150 [🧬 merge] staging 변경사항 develop에 적용
  src/main/java/org/noostak/appointment/application/recommendation/AppointmentRecommendationFacade.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberRepository.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOptionRepository.java
  src/main/java/org/noostak/auth/application/kakao/KakaoServiceImpl.java
  src/main/java/org/noostak/auth/dto/apple/AppleAccessTokenRequest.java
  src/main/java/org/noostak/auth/dto/common/SignInRequest.java
  src/main/java/org/noostak/auth/dto/common/SocialLoginRequest.java
  src/main/java/org/noostak/auth/dto/common/SocialLoginResponse.java
  src/main/java/org/noostak/group/application/ongoing/GroupOngoingAppointmentServiceImpl.java
  src/main/java/org/noostak/group/dto/request/GroupJoinRequest.java
  src/main/java/org/noostak/likes/application/LikeServiceImpl.java
Labels: 🧬 merge, 🦖 용태 🦖

#152 [🔧 fix] 약속 옵션의 생성 전략 변경
  src/main/java/org/noostak/appointment/application/recommendation/impl/AppointmentOptionCommandServiceImpl.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOptionRepository.java
  src/main/java/org/noostak/auth/dto/kakao/KakaoUserInfoResponse.java
  src/test/java/org/noostak/appointmentoption/domain/AppointmentOptionRepositoryTest.java
Labels: 🐋 장순 🐋, 🦖 용태 🦖, 🔧 fix

#153 [🧬 merge] develop -> staging
  src/main/java/org/noostak/appointment/application/recommendation/impl/AppointmentOptionCommandServiceImpl.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOptionRepository.java
  src/main/java/org/noostak/auth/dto/kakao/KakaoUserInfoResponse.java
  src/test/java/org/noostak/appointmentoption/domain/AppointmentOptionRepositoryTest.java
Labels: 🐋 장순 🐋, 🦖 용태 🦖, 🔧 fix

#156 [🔧 fix] 그룹 조회 - 그룹 예외 상속 관계 수정
  src/main/java/org/noostak/global/config/swagger/GroupSwagger.java
  src/main/java/org/noostak/global/config/swagger/SwaggerConfig.java
  src/main/java/org/noostak/group/common/exception/GroupException.java
Labels: 🐋 장순 🐋, 🔧 fix

#157 [🧬 merge] develop -> staging
  src/main/java/org/noostak/global/config/swagger/GroupSwagger.java
  src/main/java/org/noostak/global/config/swagger/SwaggerConfig.java
  src/main/java/org/noostak/group/common/exception/GroupException.java
Labels: 🐋 장순 🐋, 🔧 fix

#159 [✨feat] 그룹 가입 시 기존 약속에 포함하는 로직 추가
  src/main/java/org/noostak/appointment/application/create/AppointmentCreateServiceImpl.java
  src/main/java/org/noostak/appointment/domain/Appointment.java
  src/main/java/org/noostak/appointmentmember/application/AppointmentMemberSaveService.java
  src/main/java/org/noostak/appointmentmember/application/AppointmentMemberSaveServiceImpl.java
  src/main/java/org/noostak/appointmentmember/domain/vo/AppointmentAvailability.java
  src/main/java/org/noostak/group/application/GroupJoinServiceImpl.java
  src/main/java/org/noostak/group/application/create/GroupCreateServiceImpl.java
  src/main/java/org/noostak/group/dto/request/GroupCreateRequest.java
Labels: ✨ feat, 🦖 용태 🦖

#163 [🔧 fix] 일부 엔티티 DB에 중복 저장되는 문제 수정
  src/main/java/org/noostak/group/application/GroupJoinServiceImpl.java
  src/main/java/org/noostak/group/common/exception/GroupErrorCode.java
  src/main/java/org/noostak/likes/application/LikeServiceImpl.java
  src/main/java/org/noostak/membergroup/domain/MemberGroupRepository.java
Labels: 🦖 용태 🦖, 🔧 fix

#164 [🧬 merge] develop -> staging
  src/main/java/org/noostak/global/config/ApiPathFilter.java
  src/main/java/org/noostak/global/config/AuthInterceptor.java
  src/main/java/org/noostak/global/config/FilterConfig.java
  src/main/java/org/noostak/global/config/WebConfig.java
  src/main/java/org/noostak/global/error/handler/GlobalErrorCode.java
  src/main/java/org/noostak/global/error/handler/GlobalExceptionHandler.java
  src/main/java/org/noostak/group/application/GroupJoinServiceImpl.java
  src/main/java/org/noostak/group/common/exception/GroupErrorCode.java
  src/main/java/org/noostak/likes/application/LikeServiceImpl.java
  src/main/java/org/noostak/membergroup/domain/MemberGroupRepository.java
Labels: 🧬 merge, 🦖 용태 🦖

#166 [🧬 merge] staging 변경사항 develop에 적용
  src/main/java/org/noostak/auth/application/jwt/config/JwtTokenConfig.java
  src/main/java/org/noostak/auth/dto/apple/AppleTokenResponse.java
  src/main/java/org/noostak/auth/dto/google/GoogleUserInfoResponse.java
  src/main/java/org/noostak/global/config/ApiPathFilter.java
Labels: 🧬 merge, 🦖 용태 🦖

#167 [🔧 fix] 그룹 조회 API - 빈 리스트 반환
  src/main/java/org/noostak/NoostakApplication.java
  src/main/java/org/noostak/global/config/ApiPathFilter.java
  src/main/java/org/noostak/global/config/FilterConfig.java
  src/main/java/org/noostak/group/application/retrieve/GroupRetrieveServiceImpl.java
  src/test/java/org/noostak/group/application/GroupRetrieveServiceImplTest.java
  src/test/java/org/noostak/membergroup/MemberGroupRepositoryTest.java
Labels: 🐋 장순 🐋, 🦖 용태 🦖, 🔧 fix

#168 [🧬 merge] develop -> staging
  src/main/java/org/noostak/NoostakApplication.java
  src/main/java/org/noostak/global/config/ApiPathFilter.java
  src/main/java/org/noostak/global/config/FilterConfig.java
  src/main/java/org/noostak/group/application/retrieve/GroupRetrieveServiceImpl.java
  src/test/java/org/noostak/group/application/GroupRetrieveServiceImplTest.java
  src/test/java/org/noostak/membergroup/MemberGroupRepositoryTest.java
Labels: 🐋 장순 🐋, 🧬 merge, 🦖 용태 🦖

#171 [🧬 merge] develop -> staging
  src/main/java/org/noostak/appointment/api/CalendarController.java
  src/main/java/org/noostak/appointment/application/CalendarService.java
  src/main/java/org/noostak/appointment/application/CalendarServiceImpl.java
  src/main/java/org/noostak/appointment/application/recommendation/impl/AppointmentMemberAvailabilityQueryServiceImpl.java
  src/main/java/org/noostak/appointment/common/exception/AppointmentErrorCode.java
  src/main/java/org/noostak/appointment/util/AppointmentOptionResponseMapper.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMember.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberRepository.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberRepositoryCustom.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberRepositoryImpl.java
  src/main/java/org/noostak/global/config/AuthInterceptor.java
  src/main/java/org/noostak/global/config/swagger/CalendarSwagger.java
  src/test/java/org/noostak/appointmentmember/domain/repository/AppointmentMemberRepositoryTest.java
Labels: 🧬 merge, 🦖 용태 🦖

#175 [🔧 fix] 그룹 생성 API - 그룹 이름 검증 및 그룹 생성 로직 수정
  src/main/java/org/noostak/group/application/create/GroupCreateServiceImpl.java
  src/main/java/org/noostak/group/domain/vo/GroupName.java
  src/main/java/org/noostak/infra/DevS3ServiceImpl.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentMemberAvailabilityQueryServiceTest.java
  src/test/java/org/noostak/group/domain/vo/GroupsNameTest.java
Labels: 🐋 장순 🐋, 🔧 fix

#176 [🔧 fix] 그룹 생성 API - 그룹 이름 검증 및 그룹 생성 로직 수정
  src/main/java/org/noostak/group/application/create/GroupCreateServiceImpl.java
  src/main/java/org/noostak/group/domain/vo/GroupName.java
  src/main/java/org/noostak/infra/DevS3ServiceImpl.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentMemberAvailabilityQueryServiceTest.java
  src/test/java/org/noostak/group/domain/vo/GroupsNameTest.java
Labels: 🐋 장순 🐋, 🔧 fix

#179 [🔧 fix] Swagger 의존성 제거
  src/main/java/org/noostak/appointment/api/AppointmentController.java
  src/main/java/org/noostak/appointment/api/CalendarController.java
  src/main/java/org/noostak/appointmentmember/api/AppointmentMemberController.java
  src/main/java/org/noostak/appointmentoption/api/AppointmentOptionController.java
  src/main/java/org/noostak/auth/api/AuthController.java
  src/main/java/org/noostak/global/config/ApiPathFilter.java
  src/main/java/org/noostak/global/config/FilterConfig.java
  src/main/java/org/noostak/global/config/swagger/AppointmentMemberSwagger.java
  src/main/java/org/noostak/global/config/swagger/AppointmentOptionSwagger.java
  src/main/java/org/noostak/global/config/swagger/AppointmentSwagger.java
  src/main/java/org/noostak/global/config/swagger/AuthSwagger.java
  src/main/java/org/noostak/global/config/swagger/CalendarSwagger.java
  src/main/java/org/noostak/global/config/swagger/GroupSwagger.java
  src/main/java/org/noostak/global/config/swagger/LikeSwagger.java
  src/main/java/org/noostak/global/config/swagger/MemberSwagger.java
  src/main/java/org/noostak/global/config/swagger/SwaggerConfig.java
  src/main/java/org/noostak/group/api/GroupController.java
  src/main/java/org/noostak/likes/api/LikeController.java
  src/main/java/org/noostak/member/api/MemberController.java
Labels: 🐋 장순 🐋, 🔧 fix

#177 [♻️ refactor] 그룹 상세 - 진행 중인 중인 약속 조회 및 코드 리팩토링
  src/main/java/org/noostak/appointment/application/recommendation/impl/AppointmentMemberAvailabilityQueryServiceImpl.java
  src/main/java/org/noostak/appointment/application/recommendation/impl/AppointmentParticipantQueryServiceImpl.java
  src/main/java/org/noostak/appointment/common/exception/AppointmentErrorCode.java
  src/main/java/org/noostak/appointment/domain/Appointment.java
  src/main/java/org/noostak/appointment/domain/vo/AppointmentName.java
  src/main/java/org/noostak/appointment/util/AppointmentOptionResponseMapper.java
  src/main/java/org/noostak/appointmentmember/application/AppointmentMemberRetrieveAvailableTimesServiceImpl.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentMemberAvailableTimesResponse.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentMemberInfoResponse.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentMembersAvailableTimesResponse.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentMembersInfoResponse.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentScheduleResponse.java
  src/main/java/org/noostak/appointmentoption/application/AppointmentOptionConfirmServiceImpl.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOptionRepository.java
  src/main/java/org/noostak/group/application/GroupService.java
  src/main/java/org/noostak/group/application/ongoing/GroupOngoingAppointmentServiceImpl.java
  src/main/java/org/noostak/group/domain/vo/GroupName.java
  src/main/java/org/noostak/group/dto/response/ongoing/OngoingAppointmentResponse.java
  src/main/java/org/noostak/likes/application/LikeServiceImpl.java
  src/main/java/org/noostak/likes/domain/LikeRepositoryCustom.java
  src/main/java/org/noostak/likes/domain/LikeRepositoryImpl.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentParticipantQueryServiceTest.java
  src/test/java/org/noostak/appointmentmember/application/AppointmentMemberRetrieveAvailableTimesServiceImplTest.java
  src/test/java/org/noostak/likes/domain/LikeRepositoryTest.java
Labels: ♻️ refactor, 🐋 장순 🐋, 🦖 용태 🦖

#180 [🧬 merge] develop -> staging
  src/main/java/org/noostak/appointment/api/AppointmentController.java
  src/main/java/org/noostak/appointment/api/CalendarController.java
  src/main/java/org/noostak/appointment/application/recommendation/impl/AppointmentMemberAvailabilityQueryServiceImpl.java
  src/main/java/org/noostak/appointment/application/recommendation/impl/AppointmentParticipantQueryServiceImpl.java
  src/main/java/org/noostak/appointment/common/exception/AppointmentErrorCode.java
  src/main/java/org/noostak/appointment/domain/Appointment.java
  src/main/java/org/noostak/appointment/domain/vo/AppointmentName.java
  src/main/java/org/noostak/appointment/util/AppointmentOptionResponseMapper.java
  src/main/java/org/noostak/appointmentmember/api/AppointmentMemberController.java
  src/main/java/org/noostak/appointmentmember/application/AppointmentMemberRetrieveAvailableTimesServiceImpl.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentMemberAvailableTimesResponse.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentMemberInfoResponse.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentMembersAvailableTimesResponse.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentMembersInfoResponse.java
  src/main/java/org/noostak/appointmentmember/dto/response/AppointmentScheduleResponse.java
  src/main/java/org/noostak/appointmentoption/api/AppointmentOptionController.java
  src/main/java/org/noostak/appointmentoption/application/AppointmentOptionConfirmServiceImpl.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOptionRepository.java
  src/main/java/org/noostak/auth/api/AuthController.java
  src/main/java/org/noostak/global/config/ApiPathFilter.java
  src/main/java/org/noostak/global/config/FilterConfig.java
  src/main/java/org/noostak/global/config/swagger/AppointmentMemberSwagger.java
  src/main/java/org/noostak/global/config/swagger/AppointmentOptionSwagger.java
  src/main/java/org/noostak/global/config/swagger/AppointmentSwagger.java
  src/main/java/org/noostak/global/config/swagger/AuthSwagger.java
  src/main/java/org/noostak/global/config/swagger/CalendarSwagger.java
  src/main/java/org/noostak/global/config/swagger/GroupSwagger.java
  src/main/java/org/noostak/global/config/swagger/LikeSwagger.java
  src/main/java/org/noostak/global/config/swagger/MemberSwagger.java
  src/main/java/org/noostak/global/config/swagger/SwaggerConfig.java
  src/main/java/org/noostak/group/api/GroupController.java
  src/main/java/org/noostak/group/application/GroupService.java
  src/main/java/org/noostak/group/application/ongoing/GroupOngoingAppointmentServiceImpl.java
  src/main/java/org/noostak/group/domain/vo/GroupName.java
  src/main/java/org/noostak/group/dto/response/ongoing/OngoingAppointmentResponse.java
  src/main/java/org/noostak/likes/api/LikeController.java
  src/main/java/org/noostak/likes/application/LikeServiceImpl.java
  src/main/java/org/noostak/likes/domain/LikeRepositoryCustom.java
  src/main/java/org/noostak/likes/domain/LikeRepositoryImpl.java
  src/main/java/org/noostak/member/api/MemberController.java
  src/test/java/org/noostak/appointment/application/recommendation/AppointmentParticipantQueryServiceTest.java
  src/test/java/org/noostak/appointmentmember/application/AppointmentMemberRetrieveAvailableTimesServiceImplTest.java
  src/test/java/org/noostak/likes/domain/LikeRepositoryTest.java
Labels: 🧬 merge, 🦖 용태 🦖

#183 [♻️ refactor] 그룹 카운트 로직 수정 및 약속 상태 저장 로직 추가
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMember.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberAvailableTimesRepository.java
  src/main/java/org/noostak/appointmentoption/application/AppointmentOptionConfirmServiceImpl.java
  src/main/java/org/noostak/group/application/GroupJoinServiceImpl.java
  src/main/java/org/noostak/group/domain/Group.java
  src/test/java/org/noostak/appointmentmember/domain/repository/AppointmentMemberAvailableTimesRepositoryTest.java
  src/test/java/org/noostak/appointmentoption/application/AppointmentOptionConfirmServiceImplTest.java
  src/test/java/org/noostak/group/application/GroupCreateServiceImplTest.java
Labels: ♻️ refactor, 🦖 용태 🦖

#184 [🧬 merge] develop -> staging
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMember.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberAvailableTimesRepository.java
  src/main/java/org/noostak/appointmentoption/application/AppointmentOptionConfirmServiceImpl.java
  src/main/java/org/noostak/group/application/GroupJoinServiceImpl.java
  src/main/java/org/noostak/group/domain/Group.java
  src/test/java/org/noostak/appointmentmember/domain/repository/AppointmentMemberAvailableTimesRepositoryTest.java
  src/test/java/org/noostak/appointmentoption/application/AppointmentOptionConfirmServiceImplTest.java
  src/test/java/org/noostak/group/application/GroupCreateServiceImplTest.java
Labels: ♻️ refactor, 🦖 용태 🦖

#185 [♻️ refactor] 그룹 상세 - 확정된 약속들 조회(반환값 수정)
  src/main/java/org/noostak/appointment/domain/AppointmentRepositoryImpl.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOptionRepositoryImpl.java
  src/main/java/org/noostak/group/application/confirmed/GroupConfirmedAppointmentsServiceImpl.java
  src/main/java/org/noostak/group/dto/response/confirmed/ConfirmedAppointmentsResponse.java
  src/main/java/org/noostak/group/util/GroupConfirmedResponseMapper.java
Labels: ♻️ refactor, 🐋 장순 🐋

#186 [🧬 merge] develop -> staging
  src/main/java/org/noostak/appointment/domain/AppointmentRepositoryImpl.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOptionRepositoryImpl.java
  src/main/java/org/noostak/group/application/confirmed/GroupConfirmedAppointmentsServiceImpl.java
  src/main/java/org/noostak/group/dto/response/confirmed/ConfirmedAppointmentsResponse.java
  src/main/java/org/noostak/group/util/GroupConfirmedResponseMapper.java
Labels: 🐋 장순 🐋, 🧬 merge

#188 [♻️ refactor] 회원 탈퇴 로직 수정
  src/main/java/org/noostak/appointment/domain/Appointment.java
  src/main/java/org/noostak/appointment/domain/AppointmentHostSelectionTime.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMember.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberAvailableTime.java
  src/main/java/org/noostak/appointmentmember/domain/AppointmentMemberRepository.java
  src/main/java/org/noostak/appointmentoption/domain/AppointmentOption.java
  src/main/java/org/noostak/auth/api/AuthController.java
  src/main/java/org/noostak/auth/application/AuthInfoServiceImpl.java
  src/main/java/org/noostak/auth/domain/AuthInfo.java
  src/main/java/org/noostak/group/domain/Group.java
  src/main/java/org/noostak/likes/domain/Like.java
  src/main/java/org/noostak/likes/domain/LikeRepository.java
  src/main/java/org/noostak/member/domain/Member.java
  src/main/java/org/noostak/membergroup/domain/MemberGroup.java
  src/test/java/org/noostak/appointmentmember/domain/repository/AppointmentMemberRepositoryTest.java
  src/test/java/org/noostak/likes/domain/LikeRepositoryTest.java
Labels: ♻️ refactor, 🦖 용태 🦖

#191 [♻️ refactor] 약속 확정 - 확정된 약속 조회
  src/main/java/org/noostak/appointmentoption/api/AppointmentOptionController.java
  src/main/java/org/noostak/appointmentoption/application/AppointmentOptionConfirmedOptionServiceImpl.java
  src/main/java/org/noostak/appointmentoption/common/exception/AppointmentOptionErrorCode.java
  src/main/java/org/noostak/appointmentoption/util/AppointmentOptionConfirmedOptionConverter.java
Labels: ♻️ refactor, 🐋 장순 🐋

#192 [🧬 merge] develop -> staging
  src/main/java/org/noostak/appointmentoption/api/AppointmentOptionController.java
  src/main/java/org/noostak/appointmentoption/application/AppointmentOptionConfirmedOptionServiceImpl.java
  src/main/java/org/noostak/appointmentoption/common/exception/AppointmentOptionErrorCode.java
  src/main/java/org/noostak/appointmentoption/util/AppointmentOptionConfirmedOptionConverter.java
Labels: 🐋 장순 🐋, 🧬 merge

#194 [ 🔧fix] 그룹 중복 가입 에러 해결
  src/main/java/org/noostak/group/application/GroupService.java
Labels: 🦖 용태 🦖, 🔧 fix

#195 [🧬 merge] develop -> staging
  src/main/java/org/noostak/group/application/GroupService.java
Labels: 🦖 용태 🦖, 🔧 fix

#197 [♻️ refactor] 멤버 이름 초성을 허용하도록 수정
  src/main/java/org/noostak/appointmentmember/common/success/AppointmentMemberSuccessCode.java
  src/main/java/org/noostak/auth/common/success/AuthSuccessCode.java
  src/main/java/org/noostak/group/dto/response/confirmed/GroupConfirmedAppointmentsResponse.java
  src/main/java/org/noostak/group/dto/response/ongoing/GroupOngoingInfoResponse.java
  src/main/java/org/noostak/member/common/exception/MemberErrorCode.java
  src/main/java/org/noostak/member/domain/vo/MemberName.java
  src/test/java/org/noostak/group/application/confirmed/GroupConfirmedAppointmentsServiceImplTest.java
  src/test/java/org/noostak/member/domain/vo/MemberNameTest.java
Labels: ♻️ refactor, 🦖 용태 🦖

#198 [🧬 merge] develop -> staging
  src/main/java/org/noostak/appointmentmember/common/success/AppointmentMemberSuccessCode.java
  src/main/java/org/noostak/auth/common/success/AuthSuccessCode.java
  src/main/java/org/noostak/group/dto/response/confirmed/GroupConfirmedAppointmentsResponse.java
  src/main/java/org/noostak/group/dto/response/ongoing/GroupOngoingInfoResponse.java
  src/main/java/org/noostak/member/common/exception/MemberErrorCode.java
  src/main/java/org/noostak/member/domain/vo/MemberName.java
  src/test/java/org/noostak/group/application/confirmed/GroupConfirmedAppointmentsServiceImplTest.java
  src/test/java/org/noostak/member/domain/vo/MemberNameTest.java
Labels: 🧬 merge, 🦖 용태 🦖
